# Netlify configuration for Angular application
[build]
  # Build command - build library then demo
  command = "npm run build:lib && npm run build:demo"

  # Output directory - where Angular outputs the demo build
  publish = "dist/demo/browser"

  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Disable Netlify Angular plugin auto-detection
[[plugins]]
  package = "@netlify/plugin-angular"

  [plugins.inputs]
    # Disable auto-configuration
    enabled = false

# Redirect rules for Angular routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets - specific files
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
